const express = require('express');
const jwt = require('jsonwebtoken');
const bcrypt = require('bcryptjs');
const rateLimit = require('express-rate-limit');
const { Joi, validate } = require('../lib/validation');
const { AppError } = require('../lib/errors');
const { authenticate, authorize, ROLES } = require('../middleware/roleMiddleware');
const { createUser, findUserByUsername, normalizeRole, DB_ROLES } = require('../models/user');
const router = express.Router();
const registerSchema = Joi.object({ employee_id:Joi.number().integer().positive(), username: Joi.string().trim().min(3).max(50).required(), password: Joi.string().min(10).max(72).custom((value,h)=>Buffer.byteLength(value)<=72?value:h.error('any.invalid')).required(), full_name: Joi.string().trim().min(1).max(100).required(), email: Joi.string().trim().email().max(100).allow(''), role: Joi.string().custom((value,helpers) => normalizeRole(value) || helpers.error('any.invalid')).valid(...DB_ROLES).required() }).required();
const loginSchema = Joi.object({ username:Joi.string().trim().max(50).required(), password:Joi.string().max(72).required() }).required();
const loginLimit = rateLimit({windowMs:15*60000,limit:20,skipSuccessfulRequests:true,standardHeaders:'draft-8',legacyHeaders:false,handler:(req,res,next)=>next(new AppError('RATE_LIMITED',429))});
const loginHandler = async (req,res) => {
  const user = await findUserByUsername(req.body.username);
  if (!user || !user.is_active || !(await bcrypt.compare(req.body.password,user.password_hash))) throw new AppError('INVALID_CREDENTIALS',401);
  const role = normalizeRole(user.role);
  if (!role) throw new AppError('INVALID_CREDENTIALS',401);
  const token = jwt.sign({id:user.id,username:user.username,role,sessionVersion:user.session_version || 0},process.env.JWT_SECRET,{expiresIn:'12h',algorithm:'HS256'});
  res.json({token,user:{id:user.id,username:user.username,role}});
};
router.post('/login',loginLimit,validate(loginSchema),loginHandler);
router.post('/register',authenticate,authorize(ROLES.ADMIN),validate(registerSchema),async (req,res)=>res.status(201).json({message:'Staff account created.',user:await createUser(req.body)}));
const loginRouter = express.Router();
loginRouter.post('/',loginLimit,validate(loginSchema),loginHandler);
module.exports = router; module.exports.loginRouter = loginRouter;
