const express = require('express');
const { requestContext, errorHandler, AppError } = require('./lib/errors');
const app = express();
app.disable('x-powered-by');
if (process.env.TRUST_PROXY) app.set('trust proxy', Number(process.env.TRUST_PROXY));
app.use(requestContext);
require('./middleware/security')(app);
app.use(express.json({limit:'128kb'}));
app.get('/',(req,res)=>res.json({service:'METMMA Pharmacy API'}));
app.use('/api',require('./routes'));
app.use((req,res,next)=>next(new AppError('NOT_FOUND',404)));
app.use(errorHandler);
module.exports = app;
