import apiClient from './apiClient'
import { toSalePayload } from './salePayload'
export const dataService = {
  getProductPage: (params = {}) => apiClient.get('/products', { params }),
  getProduct: id => apiClient.get(`/products/${id}`),
  getProductSummary: () => apiClient.get('/products/summary'),
  getConfig: () => apiClient.get('/config'),
  addProduct: product => apiClient.post('/products', product),
  updateProduct: product => { const { id, _id, ...body } = product; return apiClient.put(`/products/${id || _id}`, body) },
  restockProduct: (id, body) => apiClient.post(`/products/${id}/restock`, body),
  deleteProduct: product => apiClient.delete(`/products/${product.id || product._id}`),
  recordSale: sale => apiClient.post('/sales/checkout', toSalePayload(sale)),
  getSalesHistory: (params = {}) => apiClient.get('/sales/history', { params }),
  reverseSale: (id, body) => apiClient.post(`/sales/${id}/reverse`, body),
  getEmployees: (params = {}) => apiClient.get('/employees', { params }),
  addEmployee: employee => apiClient.post('/employees', employee),
  updateEmployee: employee => { const { id, _id, ...body } = employee; return apiClient.put(`/employees/${id || _id}`, body) },
  deleteEmployee: employee => apiClient.delete(`/employees/${employee.id || employee._id}`),
  getAttendance: (id, params = {}) => apiClient.get(`/attendance/employee/${id}`, { params }),
  markAttendance: record => apiClient.post('/attendance', record),
  getRecentActivity: () => apiClient.get('/reports/recent-activity'),
  getDashboard: () => apiClient.get('/dashboard'),
  getNotifications: (params = {}) => apiClient.get('/notifications', { params }),
  readNotification: id => apiClient.post(`/notifications/${id}/read`),
  readAllNotifications: () => apiClient.post('/notifications/read-all'),
  getTransactions: (params = {}) => apiClient.get('/finances/transactions', { params }),
  getFinanceSummary: (params = {}) => apiClient.get('/finances/summary', { params }),
  addExpense: body => apiClient.post('/finances/expenses', body),
  updateExpense: (id, body) => apiClient.put(`/finances/expenses/${id}`, body),
  deleteExpense: (id, version) => apiClient.delete(`/finances/expenses/${id}`, { data: { version } }),
  getExpenseAudit: (id, params = {}) => apiClient.get(`/finances/expenses/${id}/audit`, { params })
}
