const pool = require('../db');

exports.getEmployees = async (req, res) => {
    try {
        const result = await pool.query('SELECT * FROM employees');
        res.json(result.rows);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
};

exports.getEmployeeById = async (req, res) => {
    const { id } = req.params;
    try {
        const result = await pool.query('SELECT * FROM employees WHERE id = $1', [id]);
        if (result.rows.length === 0) {
            return res.status(404).json({ error: 'Employee not found' });
        }
        res.json(result.rows[0]);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
};

exports.addEmployee = async (req, res) => {
    // Contract: first_name, last_name, role (job title), department, email,
    // salary, hire_date, phone (-> phone_number), status (-> is_active).
    // employee_id is auto-generated by the DB default (SEQ 'EMP-000001').
    const { first_name, last_name, role, department, email, salary, hire_date, phone, status } = req.body;
    try {
        const result = await pool.query(
            `INSERT INTO employees
                (first_name, last_name, role, department, email, salary, hire_date, phone_number, is_active)
             VALUES ($1, $2, $3, $4, $5, $6, $7, $8, COALESCE($9, TRUE))
             RETURNING *`,
            [first_name, last_name, role, department, email, salary, hire_date, phone || null, status === 'active' ? true : (status === 'inactive' ? false : null)]
        );
        res.status(201).json(result.rows[0]);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }       
};

exports.updateEmployee = async (req, res) => {
    const { id } = req.params;
    const fields = [
        'first_name', 'last_name', 'role', 'department', 'email',
        'salary', 'hire_date', 'phone', 'status'
    ];

    const setClauses = [];
    const values = [];
    let i = 1;

    for (const key of fields) {
        if (req.body[key] !== undefined) {
            const column = key === 'phone' ? 'phone_number' : (key === 'status' ? 'is_active' : key);
            setClauses.push(`${column} = $${i}`);
            values.push(key === 'status' ? req.body[key] === 'active' : req.body[key]);
            i++;
        }
    }

    if (setClauses.length === 0) {
        return res.status(400).json({ error: 'No fields to update' });
    }

    try {
        values.push(id);
        const result = await pool.query(
            `UPDATE employees SET ${setClauses.join(', ')}, updated_at = CURRENT_TIMESTAMP WHERE id = $${i} RETURNING *`,
            values
        );
        if (result.rowCount === 0) {
            return res.status(404).json({ error: 'Employee not found' });
        }
        res.json(result.rows[0]);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
};

exports.deleteEmployee = async (req, res) => {
    const { id } = req.params;      
    try {
        const result = await pool.query(
            'DELETE FROM employees WHERE id = $1',
            [id]
        );      
        if (result.rowCount === 0) {
            return res.status(404).json({ error: 'Employee not found' });
        }
        res.json({ message: 'Employee deleted successfully' });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
};


