const {createHash}=require('node:crypto');
const db=require('../db');
const {AppError}=require('../../lib/errors');
const {paging,dateFilter}=require('../../lib/validation');
const {minor,decimal}=require('../../lib/money');
const format=row=>({id:row.id,type:row.type,amount:row.amount,paymentMethod:row.payment_method,date:row.transaction_date,saleId:row.sale_id,receiptNumber:row.receipt_number,category:row.category,note:row.note,supplier:row.supplier,username:row.username,version:row.version});
function filters(q,values){const where=['f.deleted_at IS NULL',...dateFilter(q,values,'f.transaction_date')];if(q.type&&q.type!=='all'){values.push(q.type==='income'?['income','refund']:['expense']);where.push(`f.type=ANY($${values.length}::text[])`);}if(q.paymentMethod&&q.paymentMethod!=='all'){values.push(q.paymentMethod);where.push(`f.payment_method=$${values.length}`);}if(q.search){values.push(`%${q.search}%`);const n=values.length;where.push(`(s.receipt_number ILIKE $${n} OR f.category ILIKE $${n} OR f.supplier ILIKE $${n} OR f.note ILIKE $${n})`);}return where.join(' AND ');}
async function getTransactions(req,res){const q=req.validatedQuery,v=[],where=filters(q,v),count=(await db.query(`SELECT COUNT(*) FROM financial_transactions f LEFT JOIN sales s ON s.id=f.sale_id WHERE ${where}`,v)).rows[0].count;v.push(q.limit,(q.page-1)*q.limit);const result=await db.query(`SELECT f.*,s.receipt_number,u.username FROM financial_transactions f LEFT JOIN sales s ON s.id=f.sale_id LEFT JOIN users u ON u.id=f.created_by WHERE ${where} ORDER BY f.transaction_date DESC,f.id DESC LIMIT $${v.length-1} OFFSET $${v.length}`,v);res.json({success:true,data:result.rows.map(format),pagination:paging(q,count,result.rowCount)});}
async function getSummary(req,res){const v=[],where=['deleted_at IS NULL',...dateFilter(req.validatedQuery,v,'transaction_date')].join(' AND ');res.json((await db.query(`SELECT COALESCE(SUM(amount) FILTER(WHERE type IN ('income','refund')),0)::text AS income,(-COALESCE(SUM(amount) FILTER(WHERE type='expense'),0))::text AS expenses,COALESCE(SUM(amount),0)::text AS net,COALESCE(SUM(amount) FILTER(WHERE type='income'),0)::text AS "grossIncome",(-COALESCE(SUM(amount) FILTER(WHERE type='refund'),0))::text AS refunds FROM financial_transactions WHERE ${where}`,v)).rows[0]);}
async function audit(client,row,before,user,action){await client.query(`INSERT INTO expense_audit(transaction_id,action,before_value,after_value,user_id) VALUES($1,$2,$3,$4,$5)`,[row.id,action,before,row,user]);}
async function createExpense(req,res){
 const d=req.body;dateFilter({start:d.date},[],'date');const amount=minor(d.amount);if(amount===0n||amount>999999999999n)throw new AppError('VALIDATION',400,['amount']);
 const canonical={amount:decimal(amount),date:d.date,category:d.category,paymentMethod:d.paymentMethod,note:d.note || '',supplier:d.supplier || ''};const hash=createHash('sha256').update(JSON.stringify(canonical)).digest('hex');
 const result=await db.transaction(async client=>{
  await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`expense:${req.user.id}:${d.idempotencyKey}`]);
  const existing=(await client.query('SELECT * FROM financial_transactions WHERE created_by=$1 AND idempotency_key=$2',[req.user.id,d.idempotencyKey])).rows[0];
  if(existing){if(existing.request_hash!==hash)throw new AppError('CONFLICT',409);return{row:existing,replayed:true};}
  const row=(await client.query(`INSERT INTO financial_transactions(type,amount,payment_method,transaction_date,category,note,supplier,created_by,updated_by,idempotency_key,request_hash) VALUES('expense',-$1::numeric,$2,$3::date,$4,$5,$6,$7,$7,$8,$9) RETURNING *`,[decimal(amount),d.paymentMethod,d.date,d.category,d.note || null,d.supplier || null,req.user.id,d.idempotencyKey,hash])).rows[0];
  await audit(client,row,null,req.user.id,'created');return{row,replayed:false};
 });res.status(result.replayed?200:201).json({success:true,data:format(result.row)});
}
async function editExpense(req,res){const d=req.body;dateFilter({start:d.date},[],'date');const amount=minor(d.amount);if(!amount||amount>999999999999n)throw new AppError('VALIDATION',400,['amount']);const row=await db.transaction(async client=>{const old=(await client.query(`SELECT * FROM financial_transactions WHERE id=$1 AND type='expense' AND deleted_at IS NULL FOR UPDATE`,[req.params.id])).rows[0];if(!old)throw new AppError('NOT_FOUND',404);if(old.version!==d.version)throw new AppError('CONFLICT',409);const row=(await client.query(`UPDATE financial_transactions SET amount=-$1::numeric,payment_method=$2,transaction_date=$3::date,category=$4,note=$5,supplier=$6,updated_by=$7,updated_at=CURRENT_TIMESTAMP,version=version+1 WHERE id=$8 RETURNING *`,[decimal(amount),d.paymentMethod,d.date,d.category,d.note || null,d.supplier || null,req.user.id,old.id])).rows[0];await audit(client,row,old,req.user.id,'edited');return row;});res.json({success:true,data:format(row)});}
async function deleteExpense(req,res){await db.transaction(async client=>{const old=(await client.query(`SELECT * FROM financial_transactions WHERE id=$1 AND type='expense' FOR UPDATE`,[req.params.id])).rows[0];if(!old)throw new AppError('NOT_FOUND',404);if(old.deleted_at)return;if(old.version!==req.body.version)throw new AppError('CONFLICT',409);const row=(await client.query(`UPDATE financial_transactions SET deleted_at=CURRENT_TIMESTAMP,updated_by=$2,updated_at=CURRENT_TIMESTAMP,version=version+1 WHERE id=$1 RETURNING *`,[old.id,req.user.id])).rows[0];await audit(client,row,old,req.user.id,'deleted');});res.json({success:true});}
async function getAudit(req,res){const q=req.validatedQuery,count=(await db.query('SELECT COUNT(*) FROM expense_audit WHERE transaction_id=$1',[req.params.id])).rows[0].count;const result=await db.query(`SELECT a.id,a.action,a.before_value AS before,a.after_value AS after,a.changed_at AS date,u.username FROM expense_audit a JOIN users u ON u.id=a.user_id WHERE a.transaction_id=$1 ORDER BY a.id DESC LIMIT $2 OFFSET $3`,[req.params.id,q.limit,(q.page-1)*q.limit]);res.json({success:true,data:result.rows,pagination:paging(q,count,result.rowCount)});}
module.exports={getTransactions,getSummary,createExpense,editExpense,deleteExpense,getAudit};
