const router=require('express').Router();
const financial=require('../controllers/finincialReportController');
const compliance=require('../controllers/complianceReportControllers');
const recent=require('../controllers/recentActivityController');
const {financialReportSchema,complianceReportSchema}=require('../validators/reportValidators');
const {validate,pageQuery}=require('../../lib/validation');
const {authenticate,authorize,ROLES}=require('../../middleware/roleMiddleware');
const read=authorize(ROLES.ADMIN,ROLES.STORE_MANAGER,ROLES.PHARMACIST,ROLES.HR_OFFICER),write=authorize(ROLES.ADMIN,ROLES.STORE_MANAGER);
router.use(authenticate);
router.get('/financial',read,validate(pageQuery,'query'),financial.getFinancialReports);
router.post('/financial',write,validate(financialReportSchema),financial.createFinancialReport);
router.get('/compliance',read,validate(pageQuery,'query'),compliance.getComplianceReports);
router.post('/compliance',write,validate(complianceReportSchema),compliance.createComplianceReport);
router.get('/recent-activity',validate(pageQuery,'query'),recent.getRecentActivity);
module.exports=router;
